spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:${dev.dataSource.kind}://${dev.dataSource.host}:${dev.dataSource.port}/${dev.dataSource.db}
    username: ${dev.dataSource.username}
    password: ${dev.dataSource.password}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      host: ${dev.redis.host}

redis:
  host: ${dev.redis.host}
  port: ${dev.redis.port}

logging.level:
  org:
    hibernate.SQL: error