spring:
  profiles:
    active: dev
    include: secret, data
  batch:
    job:
      name: ${job.name:NONE}
      enabled: false
    jdbc:
      initialize-schema: always

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 20MB