spring:
  thymeleaf:
    enabled: false
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test;
#    username: sa
#    password:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:${test.dataSource.kind}://${test.dataSource.host}:${test.dataSource.port}/${test.dataSource.db}
    username: ${test.dataSource.username}
    password: ${test.dataSource.password}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  data:
    redis:
      host: ${test.redis.host}

redis:
  host: ${test.redis.host}
  port: ${test.redis.port}

logging.level:
  org:
    hibernate.SQL: info
